### ISSUE TITLE
Example txt file output

### ISSUE THREAD

**Issue by sambilbow** [vatte/art-bio#2]
Hi!

Trying to decide on purchasing a bitalino, but want to use this repository with [pyhrv](https://github.com/PGomes92/pyhrv) to analyse the txt file (ECG) for HRV.

The HRV toolbox reads txt files of [this type](https://bitalino.com/datasheets/OpenSignals_File_Formats.pdf) (OpenSignals file format). Does art-bio output its txt file in the same format?

Thanks

**Comment by vatte** [comment]
Hi! art-bio is meant mainly for real-time signal routing and feature extraction, and the text file output is currently basically an OSC (Open Sound Control) message log, with the format:
UNIX_TIME_STAMP /osc/message/header/: value(s)

I will add a sample file.

I'm not familiar with the OpenSignals file format, but based on a quick look, it seems to be intended for raw data. This could be added as an output to art-bio as well, especially if it supports events in the data for irregularly extracted features, such as the heart beat.
